name:                GitHubAPI
version:             0.1.0.0
github:              ""
license:             BSD3
author:              ""
maintainer:          ""
copyright:           ""

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Scrapes the GitHub events API

dependencies:
- base >= 4.7 && < 5
- bytestring
- utf8-string
- case-insensitive
- HDBC
- HDBC-sqlite3
- http-conduit
- http-client-tls
- http-types
- aeson
- aeson-pretty 
- json
- text
- unordered-containers


library:
  source-dirs: src

executables:
  GitHubAPI-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - GitHubAPI

tests:
  GitHubAPI-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - GitHubAPI
